# Generated by Django 5.2.5 on 2025-10-07 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(unique=True)),
                ('duracion_estimada', models.IntegerField(help_text='Duración en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('orden', models.IntegerField()),
                ('tipo_contenido', models.CharField(choices=[('teoria', 'Teoría'), ('ejemplo', 'Ejemplo'), ('ejercicio', 'Ejercicio'), ('evaluacion', 'Evaluación')], max_length=50)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='modulos.moduloestudio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.moduloestudio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
