# Generated by Django 5.2.5 on 2025-10-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_diagnosticousuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='respuestausuario',
            table='diagnostico_respuestadiagnostico',
        ),
    ]
