# Generated by Django 5.2.5 on 2025-10-07 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntafrecuente',
            options={'verbose_name': 'Pregunta Frecuente', 'verbose_name_plural': 'Preguntas Frecuentes'},
        ),
        migrations.RemoveField(
            model_name='preguntafrecuente',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='preguntafrecuente',
            name='palabras_clave',
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='pregunta',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Conversación', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('es_usuario', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='tutor_ia.conversacion')),
            ],
        ),
    ]
