# Generated by Django 5.2.5 on 2025-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_ia', '0002_alter_preguntafrecuente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
